config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'ideas#index'
  resources :ideas do
    resources :likes, shallow: true, only: [:create, :destroy]
    get :liked, on: :collection

    resources :reviews, shallow: true, only: [:create, :destroy]
  end
  # Session Routes
  resource :session, only: [:new, :create, :destroy]
  # User Routes
  resources :users, only:[:new, :create]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action(:create, :read, :update, :delete, to: :crud)

    can :crud, Idea do |idea|
      user==idea.user
    end

    can :crud, Review do |review|
      user==review.user
    end

    can(:like, Idea) do |idea|
      user.persisted? && idea.user != user
    end
    can(:destroy, Like) do |like|
      like.user == user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user, optional: true
    has_many :reviews, dependent: :nullify
    
    has_many :likes
    has_many :likers, through: :likes  , source: :user

    
    validates :title, presence: true, uniqueness: true
    validates :description, presence: true, length: {minimum: 50}
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :idea

    validates(
        :idea_id,
        uniqueness:{
            scope: :user_id,
            message: 'has already been liked'
        }
    )
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates :body, presence: true, length: {minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :ideas, dependent: :nullify
    has_many :reviews, dependent: :nullify
    has_many :likes
    
    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
      
  def current_user
    if session[:user_id].present?
      @current_user ||= User.find session[:user_id]
    end
  end
  helper_method :current_user
      
  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?
      
  def authenticate_user!
    redirect_to new_session_path, notice: 'Please sign in' unless user_signed_in?
  end
      
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_idea, only: [:show, :edit, :update, :destroy]
    before_action :authorize_user!,only:[:edit,:update,:destroy]
    
    def new
        @idea=Idea.new
    end

    def create
        @idea=Idea.new idea_params
        @idea.user = current_user
        if @idea.save
            flash[:notice]='idea created successfully!'
            redirect_to @idea
        else
            render :new
        end
    end

    def index
        @ideas=Idea.all.order(created_at: :desc)
        # @like=@idea.likes.find_by(user: current_user)
    end

    def show
        @review=Review.new
        @reviews=@idea.reviews.order(created_at: :desc)
    end

    def edit
    end

    def update
        if @idea.update idea_params
            redirect_to @idea, notice: 'Idea edited successfully!'
        else
            render :edit
        end
    end

    def destroy
        @idea.destroy
        redirect_to root_path, notice: 'Idea deleted!'
    end

    private
    def find_idea
        @idea=Idea.find params[:id]
    end

    def idea_params
        params.require(:idea).permit(:title, :description)
    end

    def authorize_user!
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @idea)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        idea= Idea.find params[:idea_id] 
        like= Like.new idea: idea, user: current_user
        if !can?(:like, idea)
            flash[:alert]='You can not like your own idea'
        elsif like.save
            flash[:notice]='idea liked'
        else
            flash[:alert]=like.errors.full_messages.join(', ')
        end
        redirect_to ideas_path
    end
    def destroy
        like = current_user.likes.find params[:id]
        if !can?(:destroy, like)
            flash[:alert]= 'You can\'t destroy a like you don\'t own'
        elsif like.destroy
            flash[:notice]='idea unliked' 
        else
            flash[:alert]='Couldn\'t unlike the idea'
        end
        redirect_to ideas_path
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!

    def create
        @idea=Idea.find params[:idea_id]
        @review=Review.new params.require(:review).permit(:body)
        @review.idea= @idea
        @review.user= @current_user

        if @review.save
            redirect_to @idea, notice: 'review added!'
        else
            render 'ideas/show'
        end
    end

    def destroy
        
        @review=Review.find params[:id]
        if can? :crud, @review
            @review.delete
            redirect_to idea_path(@review.idea), notice: 'review Deleted'
        else
            redirect_to root_path, alert: 'Not Authorized'
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by_email params[:email]
      if user&.authenticate params[:password]
        session[:user_id] = user.id
        flash[:success] = 'Logged In!'
        redirect_to root_path
      else
        flash[:danger] = 'Wrong Credentials'
        redirect_to new_session_path
      end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:success] = 'Successfully Signed Out'
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user=User.new
    end
    def create
        @user=User.new user_params
        if @user.save
            session[:user_id]=@user.id
            redirect_to root_path, notice: "Logged in!"
        else
            render :new
        end
    end
    
    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<div class='shadow-sm p-3 m-5 rounded'>
<%= form_with model:@idea, local: true do |f| %>
<% if @idea.errors.present? %>
<%= @idea.errors.full_messages.join(', ') %>
<% end%>


    <div class='form-group'>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control'%>
    </div>

    <div class='form-group'>
        <%= f.label :description %>
        <%= f.text_area :description, cols:50, rows:5, class: 'form-control' %>
    </div>


    
        <%= f.submit class: 'btn btn-primary my-2'%>
    
<%end%>
</div>

app/views/ideas/edit.html.erb
<div class="m-5">
<h1>Edit Idea</h1>

<%=render 'form' %>
</div>

app/views/ideas/index.html.erb
<div class="container-fluid">
    
    <% @ideas.each do |i| %>
        <div class="p-2 my-3">
            
            <div class="me-auto">
                <strong><%=link_to i.title, idea_path(i.id), class: 'link-dark'%></strong>
                <p class="card-text"><%=i.description%></p>
                <a href="#">By: <%= i.user&.full_name|| "DELETED" %></a> 
                <% like = i.likes.find_by(user: current_user)%>
                <% if like.present? %>
                    <%= link_to 'unlike', like_path(like),method: :delete, class: "btn btn-outline-dark"  %> 
                <% else %>  
                    <%= link_to 'like', idea_likes_path(i), method: :post, class: "btn btn-outline-dark"  %> 
                <% end %>
                <div class='d-flex justify-content-end'>
                    <small>
                        Liked by: <%= i.likes.count %>
                    </small>                 
                </div>            
            </div>

        <hr>
    <%end%>
    
</div>

app/views/ideas/new.html.erb
<div class="m-5">
<h1>New Idea</h1>

<%=render 'form' %>
</div>

app/views/ideas/show.html.erb
<div class='m-5 p-2'>

    <h3> <%=@idea.title%> </h3>
    <p> <%=@idea.description%> </p>
    <%if can? :crud, @idea%>
    <%= link_to("Edit",edit_idea_path(@idea.id), class: 'btn btn-primary my-2')%>
    <%end%>
    <%if can? :crud, @idea%>
    <%= link_to("Delete",idea_path(@idea), method: :delete, data:{confirm: "Are you sure ?"}, class: 'btn btn-primary my-2')%>
    <%end%>

    <%# reviews %>
    <%# NEW %>
    <div class='shadow-sm p-3 m-3 round'>
        <%= form_with model:[@idea, @review], local: true do |f| %>
            
            <div class='form-group'>
                <%= f.label 'Leave a review:' %>
                <%= f.text_area(:body, class: 'form-control', placeholder: 'Your thoughts here' )%>
            </div>

            <%= f.submit class: 'btn btn-primary mt-2'%>
        <% end %>
    </div>

    <%# LIST of reviews %>
    <h2 class="display-6 m-3"> Here's what other people thinking: </h2>
    <% @reviews.each do |review| %>
    <div class="list-group m-3">
    <li class="list-group-item list-group-item-light">
        <%= review.body %>
        <small>
        <em>
        <p class='my-2'>Reviewed by: <%= review.user&.full_name ||"DELETED"%>
        <br><%= time_ago_in_words(review.updated_at)%> ago</p>
        </em>
    </small>
        <%# DELETE review%>
        <%if can? :crud, review%>
            <div class="d-flex justify-content-end">
                <%=link_to "Delete", review_path(review), 
                method: :delete, data: {confirm: 'Are you sure?'}, 
                class: 'btn btn-danger'%>
            </div>
        <%end%>
    </li>
    
    </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaFactory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
  </head>

  <body>
    <%=render 'shared/navbar'%>
    <%=render 'shared/alerts'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<div class='container'>
  <% flash.each do |type, message| %>
    <div class='shadow-lg p-3 mb-5 bg-<%= type %> rounded'>
      <%= message %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
    <div class="nav-item">
    <img src="https://pics.freeicons.io/uploads/icons/png/4094795401543238922-512.png"
    width="50">
    <p><%=link_to 'Idea Factory', root_path, class: 'link-dark'%></p>
    
    </div>
    
    
    <div class='container justify-content-end'>
                
        <% if user_signed_in? %>
        
        <div class="nav-item m-2">
            <strong>Hi, <%=current_user.full_name %> </strong>
        </div>
        
        <div>
            <%= link_to "Logout", session_path, method: :delete,
            data: {confirm: 'Are you sure you want to log out?'}%>
        </div>
        
        <% else %> 

        <div class="nav-item">
            <%=link_to 'Sign In', new_session_path, class: 'nav-link'%>
        </div>
        
        <div class="nav-item">
            <%=link_to 'Sign Up', new_user_path, class: 'nav-link'%>
        </div>
        <%end%>
        
        <div class="nav-item ml-1">
            <%=link_to 'New Idea', new_idea_path, class: 'btn btn-outline-dark'%>
        </div>
    </div>
</nav>
<hr>

app/views/users/new.html.erb
<h1>Sign Up Form</h1>
<div class='shadow-sm p-3 mb-5 rounded'>
<%= form_with model: @user, local:true do |f|%>
<% if @user.errors.any? %>
<p>
    <%= @user.errors.full_messages.join(', ')%>
</p>
<% end %>

<div class='form-group'>
    <%= f.label :first_name  %> 
    <%= f.text_field :first_name  %> 
</div>
<div class='form-group'>
    <%= f.label :last_name  %> 
    <%= f.text_field :last_name  %> 
</div>
<div class='form-group'>
    <%= f.label :email  %> 
    <%= f.email_field :email  %> 
</div>
<div class='form-group'>
    <%= f.label :password %>
    <%= f.password_field :password %>
</div>
<div class='form-group'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
</div>

<%= f.submit "Sign up", class: 'btn btn-success'%>
<% end %>
</div>